### ISSUE TITLE
[Bug]: Saddles disappear

### ISSUE THREAD

**Issue by ISolox** [Mrbysco/ChocoCraft4#82] opened 2024-07-11 23:09 UTC
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Fabric 0.15.11

### Minecraft version

1.21

### Mod version

0.11.4

### Java version

Java 21

### Issue Description

Saddles seemingly disappear off of tamed Chocobos in multiplayer. Not sure if it's the specific cause, but it seems to happen more when a player logs off the server for awhile and comes back.

**Comment by Mrbysco** [comment] 2024-07-28 09:34
Duplicate of https://github.com/Mrbysco/ChocoCraft4/issues/82

**Closed as completed by Mrbysco** 2024-07-28 09:34 UTC
Labels: bug

**Comment by james5922** [comment] 2024-09-25 21:57
Huh? Duplicate of itself?

**Comment by Mrbysco** [comment] 2024-09-25 22:31
Huh, Pretty sure at that moment there was another issue, but I can't find it atm
